sudo: false

addons:
  firefox: "64.0"

language: node_js

node_js:
  - '10'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm test
